version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566" 
      - "4572:4572" 
    environment:
      - SERVICES=s3
      - DEBUG=1
      - EXPERIMENT_NAME=nyc-duration
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_
    volumes:
      - "./localstack:/var/lib/localstack"
      - "./scripts:/docker-entrypoint-initaws.d"